version: '3'
services:
  transmitter:
    container_name: transmitter 
    ipc: "shareable"
    build: transmitter/ 
  receiver: 
    container_name: receiver
    ipc: "service:transmitter"
    build: receiver/
